<a href="https://colab.research.google.com/github/MarcosLaydner/ds_repo/blob/master/Lab_1/Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Create a (4 x 2) integer array and print it's attributes

In [26]:
import numpy as np

a = np.array([[0, 1],
             [4, 5],
              [2, 3],
              [7, 8]])

print(type(a))
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.itemsize)
print(a.nbytes)

<class 'numpy.ndarray'>
int64
2
(4, 2)
8
64


# 2. Create an array of dimension (1,10) and sort it in ascending and descending order

In [21]:
a = np.array([2,6,7,8,23,234,2,5,0,144])
print(a.shape)

a.sort()
print(a)
print(a[::-1])

(10,)
[  0   2   2   5   6   7   8  23 144 234]
[234 144  23   8   7   6   5   2   2   0]


# 3. Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [32]:
a = np.array( [1, 2, 3, 4, 5, 6, 7, 8, 9] )
print(a)
# new_a = np.reshape(a, (-1, 2))
# print(new_a)
a.shape = (a.size//3, 3)
print(a)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 4. Stack two arrays of any size horizontally and vertically

In [39]:
a = np.array( [1, 2, 3, 4] )
b = np.array( [5, 6, 7, 8] )
arrays = [a, b]
print(np.stack(arrays, axis=0))
print(np.stack(arrays, axis=1))


[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


# 5. Create two array of same size and find commom elements

In [44]:
a = np.array( [1, 2, 3, 4] )
b = np.array( [8, 9, 7, 2] )

print(np.intersect1d(a, b))

[2]


# 6. Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [53]:
a = np.random.randint(100,  size=(2, 5))

print(a)
print('\n')
print(np.amax(a, axis=0))
print('\n')
print(np.amax(a, axis=1))

[[ 1  8 98 32 98]
 [79 55 83 15 49]]


[79 55 98 32 98]


[98 83]


# 7. Create an array of size 100 and compute the mean, median, standard deviation.

In [57]:
a = np.random.randint(100,  size=(1, 100))

print(a)
print(np.mean(a))
print(np.median(a))
print(np.std(a))

[[64 25 93 74 59 82  5 98 25 49 90 49 18 35 66  3  6 63 89 27  9 27 17 87
   5 81 89  2 92 20 77 80  6 45 29 76 14 29 25  8 56 73 40 95 84 50 73 51
  61  6 22 88 23 42 23 24 64 99  5 62 93 20 29 37 72 72 79 51 90 51 78  3
   9 36 84 49 32 89 28 50 64 72 43 60 70 22 27 27 89 81 89 36  6 39 80 26
  77  3 52 27]]
49.21
49.5
29.44734113634031


# 8. Normalize a 5x5 random matrix

In [58]:
a = np.random.randint(100,  size=(5, 5))
print(a)
print('\n')

a_max, a_min = a.max(), a.min()
a = (a - a_min)/(a_max - a_min)

print(a)


[[23  8 26 80 16]
 [83 95 86 26 67]
 [41  0 64 84 44]
 [14 11 79 48 33]
 [73 55 50 52  0]]


[[0.24210526 0.08421053 0.27368421 0.84210526 0.16842105]
 [0.87368421 1.         0.90526316 0.27368421 0.70526316]
 [0.43157895 0.         0.67368421 0.88421053 0.46315789]
 [0.14736842 0.11578947 0.83157895 0.50526316 0.34736842]
 [0.76842105 0.57894737 0.52631579 0.54736842 0.        ]]


# 9. Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

In [78]:
a = np.random.randint(100,  size=(4,4,3))
b = np.random.randint(100,  size=(4, 4))

print(a)
print('\n')
print(b)
print('\n')

c = np.split(ary=a, axis=2, indices_or_sections=3)

c1, c2, c3 = c[0], c[1], c[2]

multi = b*c1
multi = multi*c2
multi = multi*c3

print(multi)

[[[46 32  1]
  [53 52 77]
  [78 95 63]
  [40 83 15]]

 [[69 78 49]
  [ 0 11 64]
  [65 46 39]
  [31 20 20]]

 [[14 16 70]
  [97 79 68]
  [72 65 36]
  [59 56 31]]

 [[54 99 60]
  [39 81 20]
  [31 81 61]
  [ 6  6  4]]]


[[91 39 11 22]
 [90 73 13 66]
 [67 94 48 96]
 [38 40 16  5]]


[[[  133952    57408    16192    32384]
  [19099080 15491476  2758756 14005992]
  [31277610 43882020 22407840 44815680]
  [ 1892400  1992000   796800   249000]]

 [[23998338 10285002  2900898  5801796]
  [       0        0        0        0]
  [ 7812870 10961340  5597280 11194560]
  [  471200   496000   198400    62000]]

 [[ 1426880   611520   172480   344960]
  [46897560 38039132  6774092 34391544]
  [11288160 15837120  8087040 16174080]
  [ 3892112  4096960  1638784   512120]]

 [[29189160 12509640  3528360  7056720]
  [ 5686200  4612140   821340  4169880]
  [10262457 14398074  7352208 14704416]
  [    5472     5760     2304      720]]]


In [81]:
a * b[:,:,None]

array([[[4186, 2912,   91],
        [2067, 2028, 3003],
        [ 858, 1045,  693],
        [ 880, 1826,  330]],

       [[6210, 7020, 4410],
        [   0,  803, 4672],
        [ 845,  598,  507],
        [2046, 1320, 1320]],

       [[ 938, 1072, 4690],
        [9118, 7426, 6392],
        [3456, 3120, 1728],
        [5664, 5376, 2976]],

       [[2052, 3762, 2280],
        [1560, 3240,  800],
        [ 496, 1296,  976],
        [  30,   30,   20]]])